### PR TITLE
Fix autoloading

### PR DESCRIPTION
**Pull request by jeboehm**
This ensures that PluginIsManagedByComposer.php is loaded when using the Shopware production template. The autoload-dev section is skipped in most cases. That causes ".... already defined" errors in composer environments, because src/NRLEJPostDirektAutocomplete.php is loading its own bundled vendor folder when __NR_POSTDIREKT_AUTOCOMPLETE_MANAGED_BY_COMPOSER is not defined.

### CODE REVIEW

**Comment by ngolatka** [comment]
_Internal refs PDSW-104 / PDSUP-1060181_

**Comment by powli** [comment]
@jeboehm Can you please elaborate on how you install the module to receive the mentioned error?

When installing the module via standard composer installation (https://github.com/netresearch/deutschepost-module-autocomplete-sw6#from-packagist) there should not be a vendor folder inside of the module directory at all.

**Comment by jeboehm** [comment]
Hi @powli
i'm installing the plugin using the Friends Of Shopware Proxy: `composer require store.shopware.com/nrlejpostdirektautocomplete`
This way it has the vendor folder in it.

**Comment by powli** [comment]
Thanks for the info, I'll investigate - it looks like an issue with scoping the dependencies.

**Comment by powli** [comment]
@jeboehm quick update: we were able to produce a version without the issue. We will release a new package version soon for that reason.

**Comment by MDSLKTR** [comment]
Any ETA?

**Comment by powli** [comment]
@MDSLKTR should be solved with 1.3.3 release

**Pull request closed without merging**
